#!/usr/bin/env bash
# DR drill — region rebuild.
#
# Tears one region's workload down to nothing and rebuilds it from IaC + git,
# proving the workload is reconstructible. Sequences the phases, times each,
# captures CLI evidence, and writes docs/evidence/DR_REPORT.md.
#
#   Usage:  scripts/dr/dr-drill.sh <region>
#
# DESTRUCTIVE: phase 1 destroys the live EKS cluster in <region>. The script
# requires the operator to type the region name to confirm before it proceeds.
#
# Plan + failure-mode matrix: docs/dr-plan.md

set -euo pipefail

REGION="${1:-}"
[ -n "$REGION" ] || { echo "usage: $0 <region>" >&2; exit 2; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

CLUSTER="aegis-stateless-${REGION}"
EVIDENCE_DIR="docs/evidence"
REPORT="${EVIDENCE_DIR}/DR_REPORT.md"
LOG="${EVIDENCE_DIR}/dr-drill-$(date -u +%Y%m%dT%H%M%SZ).log"
mkdir -p "$EVIDENCE_DIR"
exec > >(tee -a "$LOG") 2>&1

ts()  { date -u +%Y-%m-%dT%H:%M:%SZ; }
now() { date -u +%s; }
say() { printf '\n=== %s === %s\n' "$1" "$(ts)"; }
dur() { printf '%dm %ds' $(( ($2 - $1) / 60 )) $(( ($2 - $1) % 60 )); }

# ---- phase 0 — baseline ---------------------------------------------------
say "PHASE 0 — baseline"
aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION" >/dev/null
kubectl get pods -n greeter -o wide
ready="$(kubectl get deploy aegis-greeter -n greeter -o jsonpath='{.status.readyReplicas}' 2>/dev/null || echo 0)"
[ "${ready:-0}" -ge 1 ] || { echo "baseline FAILED — greeter has no ready replicas; aborting" >&2; exit 1; }
echo "baseline OK — greeter readyReplicas=$ready"
T0="$(now)"; T0_ts="$(ts)"

# ---- confirmation ---------------------------------------------------------
say "CONFIRM"
echo "Phase 1 runs 'make destroy-region REGION=$REGION' — this DESTROYS the"
echo "live EKS cluster '$CLUSTER' and everything in it."
read -r -p "Type the region name ($REGION) to proceed: " confirm
[ "$confirm" = "$REGION" ] || { echo "confirmation mismatch — aborting" >&2; exit 1; }

# ---- phase 1 — teardown ---------------------------------------------------
say "PHASE 1 — teardown"
make destroy-region REGION="$REGION"
T1="$(now)"; T1_ts="$(ts)"

# ---- phase 2 — rebuild ----------------------------------------------------
say "PHASE 2 — rebuild"
make regional-one REGION="$REGION"
T2="$(now)"; T2_ts="$(ts)"

# ---- phase 3 — reconverge -------------------------------------------------
say "PHASE 3 — reconverge"
aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION" >/dev/null
echo "waiting for ArgoCD to reconverge the greeter workload (up to 15 min)..."
deadline=$(( $(now) + 900 ))
until [ "$(kubectl get deploy aegis-greeter -n greeter -o jsonpath='{.status.readyReplicas}' 2>/dev/null || echo 0)" -ge 1 ]; do
  [ "$(now)" -lt "$deadline" ] || { echo "reconverge TIMED OUT after 15 min" >&2; exit 1; }
  sleep 15
done
kubectl get pods -n greeter -o wide
T3="$(now)"; T3_ts="$(ts)"

# ---- phase 4 — report -----------------------------------------------------
say "PHASE 4 — report"
TEARDOWN="$(dur "$T0" "$T1")"
REBUILD="$(dur "$T1" "$T2")"
RECONVERGE="$(dur "$T2" "$T3")"
RTO="$(dur "$T1" "$T3")"

cat > "$REPORT" <<EOF
# DR drill report — region rebuild

> Generated by \`scripts/dr/dr-drill.sh $REGION\` on $(ts).
> Plan + failure-mode matrix: [\`../dr-plan.md\`](../dr-plan.md).

## Result

| Phase | From → to | Duration |
|---|---|---|
| 0 — baseline | — ($T0_ts) | — |
| 1 — teardown ($CLUSTER destroyed) | $T0_ts → $T1_ts | $TEARDOWN |
| 2 — rebuild (Terraform re-apply) | $T1_ts → $T2_ts | $REBUILD |
| 3 — reconverge (ArgoCD syncs from git) | $T2_ts → $T3_ts | $RECONVERGE |
| **Measured RTO** (teardown start → workload back) | $T1_ts → $T3_ts | **$RTO** |

The workload was reconstructed from Terraform state + git with no manual
intervention beyond running this script. Terraform state is the source of
truth; ArgoCD converged the cluster from zero.

## Grafana evidence — capture manually

The live dashboard is not durable evidence (the cluster is torn down after the
demo; Grafana Cloud's free tier retains data ~14 days). Capture it now, while
the drill window is still queryable:

1. Open the \`aegis-greeter-overview\` dashboard.
2. Set the time range to **$T0_ts → $(ts)**.
3. Screenshot the Request rate / Latency / Pod-readiness panels — they show the
   metric drop at teardown, the flat gap through the rebuild, and the recovery
   at reconverge.
4. Save as \`grafana-dr-curve.png\` in this directory and commit it.

## CLI log

Full phase-by-phase CLI output: \`$(basename "$LOG")\` (this directory).
EOF

say "DONE — measured RTO $RTO"
echo "report: $REPORT"
echo "log:    $LOG"
echo "Next: capture the Grafana screenshot per the report, then commit docs/evidence/."
